apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-app
  namespace: demo-cluster
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 15.0.0  # Change to an older version that is not OCI-based
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
        namespace: flux-system
  values:
    service:
      type: NodePort
